/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ffitest_ffitest_Fibonnacci */

#ifndef _Included_com_ffitest_ffitest_Fibonnacci
#define _Included_com_ffitest_ffitest_Fibonnacci
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ffitest_ffitest_Fibonnacci
 * Method:    fib
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ffitest_ffitest_Fibonnacci_fib
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
